apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:24pXwLRXJPFO4aFhW3c1e/J01eL2HqqtODb5icc6x3w7Ni2bZIjXxw==,iv:kzYG1sM0CrPTIx140hyxQdR1zmv+YJDPCctG2mYggXc=,tag:ZlIBXGT8aLIesY/xKukiKA==,type:str]
sops:
  age:
    - recipient: age1g0lzngewnkwxhcyq70rrnlxcungjzcd337we9xur5r8cxtveudxqpm9zyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOWJjZ0h0d2c4dDAwaTNX
        cEtSZHVQTFdFNW5lek4xcWtCV0liN0hWU1hRClQvODlFYUZQVVNFWlUxVmhsSndw
        c0trUUZaRm9uVXlaSURHL0h2QjR6Q2cKLS0tIGFUZEhxTmxnUlRpNHR2cnllM3Ji
        VmcwVmdPK0theGdOa0pJRHZrenUwR1UK6Myp5qo3/tQmfAao44oN95V1xQlb/m/E
        pxJrDGffdg9bdFcYat+VDtHKBmvw1UwwzevJiR58QYID7KQEGGclTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:21:22Z"
  mac: ENC[AES256_GCM,data:6KkFofasxvCYbvKwZwY/7WM9cL8ctLLW2wflV7UtGbOePbAbnTVrXBweKjPgk0AApv2x3WOPRYO//WN/dR6iQh9ocVgqjnoclE0fXgT4Y0m6aX0kyNWlpi07IqnbpGYuAWez2g9WmFFmgxPkSfZkUi2V2ga8KhbWKNDvCeOX4yU=,iv:WMC2oeGdKbHOil+stiVcdCCceqnCo/3Q6E4L7KxwOl0=,tag:lnO0UCAhv5cT8QCQ5nIzWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
