apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:XQNGiQXo4dmxxQ==,iv:YGN2v9XFhal90cWMGO4taxntt6aXlbBYq/tZM5unTBQ=,tag:Jwkwr3Lr7m75JQO2YkACyg==,type:str]
sops:
  age:
    - recipient: age1g0lzngewnkwxhcyq70rrnlxcungjzcd337we9xur5r8cxtveudxqpm9zyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdFBQWHJNTlFrckRxRWpC
        L3RSVWM1MUlheUdsUzR3cmJXUTFRdjFyMVRJCmdrU3J6VUkxVWc0dUx5S1JTL2Ft
        Rzd0QjMzQnBXTjRtN1NOTHY2eEkxMW8KLS0tIFZMV3Fkbk95V0dBR3B5bU1WM2cr
        NFdkYVVNTDE2QWRTSDFLQnVsOHVnRW8KsLD6C2kplOnAJxVM/FhRTF+gYMZxsX28
        KHBXsvurPSOIBN0sk7zepUWNOmNWbGc2GUu+xZphyI5ZI/QvRnWYUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:21:22Z"
  mac: ENC[AES256_GCM,data:NYXAnuSUpdoev/yyJeFytc/eokbhZrvHA4lelWzoMZdKStpEElXl8/vOfKZIWpmZpeBBhmGFF7xZ8O06ziyGzLAlGz46HOD0T96PUrwxEZ0uTfvAVdI//Xj82LgQsCWN+7hKKLHw/xPuFLTyiOm4cz/c6MAe9D/2HxDkUtoU79Q=,iv:pFHgXsYEhhoi7jl8EWuu9p2Bhqo/EISQitCtofJ9ED8=,tag:cI6A4WEznUOVMetSEos0mQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
