apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wah32ZxGJmU3f2Z4kEJGsazvXtwSjVhStO+2AZNWC4U=,iv:pGXMI0jiAoIMuyTPVhQaoULS+1y36oJocmn02Fq6yU8=,tag:TAahE57B8dmeMLBLTUkLzA==,type:str]
sops:
  age:
    - recipient: age1g0lzngewnkwxhcyq70rrnlxcungjzcd337we9xur5r8cxtveudxqpm9zyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGg5cnNLRGJOZ3hmbEg5
        Z1A0L0MwWVY2ZXlPb1UxYkd0VnJIbmZRdUFFCkVhWmplQm52L1NRblZYOTdSUGZQ
        bk1wV0cvRG1uU3NSS3d3WUlnWkJWb2MKLS0tIFlseU54MGFVUFBqMDZkMEdXUGx6
        OHVjMDVMQWgvbWg5QUxpMkZPTlVaNzQKCLQ1/hVHvzhlKCEsCH0CYeyba5FLZlHJ
        0ej8UJS4xWfxVSmD/sZAZrZtzZTBm4FfdhqHazanN8uAbpH/CCyfTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:21:22Z"
  mac: ENC[AES256_GCM,data:gCls5uxi8Kz6ftEWPprZ6Z5tNrknoSPz8nnth6zAruc2KVYtFOi3hwbQLBHcNB0ySGtoQbMH462UinNozcEvBIY5ZBfcJs/cNfpk62lDZG7agcL3AI8iiJ70QlxPJESlLqF+wfMSVt/7F2Tps742heWBqQMLlJt069BW4I45cME=,iv:HWY1ljQFYyC0+QgPcGvYAH2WpGAabU5TSrj2ZSkt+HY=,tag:GLqbFRvrh0aq7nqgid8RiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
