apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:NRdzZ/uCkiPUHRtAO9NltueAf09eumSZ7YFjB62y2PdtbgvIbHdU8YV5+3y+lvs/YJIRSE1RpoDr6y9PbCvPZjuzn7OYQVylhCe1WyAUnVssDKEfl2KbCqkTNWbkIvlVnbfnb14AujEkPXk7ZD35TT1DFgcPA2fdhtVuBslM0pDXNpy2WHbJZUNVHTUD2oA/JIYo6Guobb2WGeMlNt80nMahdV1Dg8ktn6/eETW+zvw/x49I,iv:VCooBQZmwPfE1UrAyNZJ02vfEriym2uN115naSQXIHM=,tag:kar59YWY1EMVmyRBfGDEjg==,type:str]
sops:
  age:
    - recipient: age1g0lzngewnkwxhcyq70rrnlxcungjzcd337we9xur5r8cxtveudxqpm9zyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYnVoTWw5MFFtN1p2bXdF
        cmVTMmNFbFJSdEYwczJFdG9KVnlzbytlNUVBCjd3TWlUNFo4Vy9Ba05FaEJ4eGZ1
        Z0tyQ1h5ekFmU1F6bkdjWlVTMnlDMkkKLS0tIHkrYldkaEoxaEVFM0xxWHdEQXpG
        VXpkZ3NwcUlKaS9VNFVHc3V3S1hXczQKA5O4ODYNN6jrx00AfnibjAQJX9vI/j2V
        uy/KVb2jdo9FHM0G++loadMSiz/XsnaRTqIo3DPfeaMUPtsTf5Njyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:21:22Z"
  mac: ENC[AES256_GCM,data:tIr8BHSNpj38MAIkg050TE4+xfc8sYlz2HVFpmmuDFn4bMuUcWdqXwZeLU7Y5IIyqbAd9PI03dZ/4cMX3JmA7Ct+s0decx9MD9G6aIqDI6vSXi8PrnFXpAA6iZiDEVTqJftRemgIUCu4FAnss81wlT/gcOf/6E9yQLXnrZoK7FE=,iv:9ovsZZ+Iq1fRExezOxLQFB9P8isZO27UK8aaqwDtvIY=,tag:JXmicLVtxKnaPwUpteJ1yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
