apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vi+IPFaxyLUU1Swezsr2slC596KBVikz03MA3fTeE1pnLqnmCpzQSQ==,iv:zXmylccWeaPI5mUCMnTPStH3QMDag44P02SvqQNoUVE=,tag:M+riRM8Mz1CfrN7FYHZ3VQ==,type:str]
sops:
  age:
    - recipient: age1g0lzngewnkwxhcyq70rrnlxcungjzcd337we9xur5r8cxtveudxqpm9zyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbDIybFlmVUYwR2dCR3FW
        TEIvVDkxZ2V4WGc3aTM1U1dwR2FnSHIzYVJRCmRwbzZSSWhVZWFuRjgrcDlxUkF0
        UW8yMWxNNmJqaTE4OGVQRCt4Wis5VEUKLS0tIHZXS2xqTHE0ZWNxTWE2UnhoYlNS
        RE5hbVB4TEFzSDBrbE53OWp6K05TcUEKu7KJOUwTws4or3Me8ksNkSt0VGgSxtdG
        a2dPK+xe69cfleZOopf2HrkumSnwXJjKOmTHQqMkcsZm2spofmxdXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:21:22Z"
  mac: ENC[AES256_GCM,data:cVqajF7h0vns5hUSl7Je61yVRaRdjEllcRIuaOx0MulxKH7bgoeymtOU+Wey/iVwLDJPGFEfQ2MSZ3kOZxnKycbDoQ5+bd4RT3WdeoRN0XWaaTQJ5sQh5qeXxXsb7YNCClEmbuRtq6K6+4HQqyt0NaorbNNEiW1UDxYUDLd7F54=,iv:dQh/Y5G8PKSWGNnI1WlD6Xlxogp4fyaf6rn2ka00Frg=,tag:/BYsjAf2mf9C71rr1ok5Mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
